b:
  cuts:
    - [HadronConeExclTruthLabelID, ==, 5]
c:
  cuts:
    - [HadronConeExclTruthLabelID, ==, 4]
u:
  cuts:
    - [HadronConeExclTruthLabelID, ==, 0]

Hbb:
  cuts:
    - [R10TruthLabel_R22v1, ==, 11]
Hcc:
  cuts:
    - [R10TruthLabel_R22v1, ==, 12]
top:
  cuts:
    - [R10TruthLabel_R22v1, ==, 1]
qcd:
  cuts:
    - [R10TruthLabel_R22v1, ==, 10]
