jets:
  inputs:
    - pt
    - eta
    - mass
  labels:
    - R10TruthLabel_R22v1
    - R10TruthLabel_R22v1_TruthJetMass
    - R10TruthLabel_R22v1_TruthJetPt

tracks:
  inputs:
    - d0
    - z0SinTheta
    - dphi
    - deta
    - qOverP
    - IP3D_signed_d0_significance
    - IP3D_signed_z0_significance
    - phiUncertainty
    - thetaUncertainty
    - qOverPUncertainty
    - numberOfPixelHits
    - numberOfSCTHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
    - numberOfInnermostPixelLayerSharedHits
    - numberOfInnermostPixelLayerSplitHits
    - numberOfPixelSharedHits
    - numberOfPixelSplitHits
    - numberOfSCTSharedHits
    - numberOfPixelHoles
    - numberOfSCTHoles
  labels:
    - truthOriginLabel
    - truthVertexIndex

flow:
  inputs:
    - pt
    - energy
    - deta
    - dphi
